fpath+=~/.zfunc

# Path to your oh-my-zsh installation.
export ZSH=/Users/do6kai/.oh-my-zsh

# for homebrew
export PATH=/usr/local/bin:$PATH

# for the agnoster theme
export DEFAULT_USER='do6kai'

ZSH_THEME="agnoster"

ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

plugins=(
    git
    extract
    npm
)

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'

alias l='ls -lh'
alias ll='ls -lha'
alias e='$EDITOR'
