fpath+=~/.zfunc

# Path to your oh-my-zsh installation.
export ZSH=/Users/merdog/.oh-my-zsh

ZSH_THEME="bullet-train"

BULLETTRAIN_PROMPT_ORDER=(
    dir
    git
)
BULLETTRAIN_PROMPT_CHAR=']'

ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

plugins=(git extract)

source $ZSH/oh-my-zsh.sh

export PATH=$PATH':/Users/merdog/.cargo/bin'

export EDITOR='nvim'

alias l='ls -lh'
alias ll='ls -lha'
alias e='$EDITOR'
